WITH Final AS (
    SELECT [Datekey]
        ,[FullDateLabel]
        ,[DateDescription]
        ,[CalendarYear]
        ,[CalendarYearLabel]
        ,[CalendarHalfYear]
        ,[CalendarHalfYearLabel]
        ,[CalendarQuarter]
        ,[CalendarQuarterLabel]
        ,[CalendarMonth]
        ,[CalendarMonthLabel]
        ,[CalendarWeek]
        ,[CalendarWeekLabel]
        ,[CalendarDayOfWeek]
        ,[CalendarDayOfWeekLabel]
        ,[FiscalYear]
        ,[FiscalYearLabel]
        ,[FiscalHalfYear]
        ,[FiscalHalfYearLabel]
        ,[FiscalQuarter]
        ,[FiscalQuarterLabel]
        ,[FiscalMonth]
        ,[FiscalMonthLabel]
        ,[IsWorkDay]
        ,[IsHoliday]
        ,[HolidayName]
        ,[EuropeSeason]
        ,[NorthAmericaSeason]
        ,[AsiaSeason]
    FROM {{ source('ContosoRetailDW', 'DimDate')}}
)
SELECT *
FROM Final  
